<?php namespace Jakten\Helpers;

/**
 * Class Prices
 * @package Jakten\Helpers
 */
class Prices
{
    /**
     * @constant CURRENCY_SUFFIX
     */
    const CURRENCY_SUFFIX = ' kr';

    /**
     * CAR
     */
    const DRIVING_LESSON_CAR = 'DRIVING_LESSON_CAR';
    const RISK_ONE_CAR = 'RISK_ONE_CAR';
    const RISK_TWO_CAR = 'RISK_TWO_CAR';
    const ENROLLMENT_CAR = 'ENROLLMENT_CAR';
    const LITERATURE_CAR = 'LITERATURE_CAR';
    const MANDATORY_EXPENSES_CAR = 'MANDATORY_EXPENSES_CAR';
    const BORROW_CAR_DRIVING_TEST = 'BORROW_CAR_DRIVING_TEST';
    const DRIVING_TEST_WARM_UP_CAR = 'DRIVING_TEST_WARM_UP_CAR';
    const INTRODUCTION_CAR = 'INTRODUCTION_CAR';
    const THEORY_LESSON_CAR = 'THEORY_LESSON_CAR';
    const ENGLISH_RISK_ONE = 'ENGLISH_RISK_ONE';
    const INTRODUKTIONSKURS_ENGLISH = 'INTRODUKTIONSKURS_ENGLISH';
    const RISK_ONE_ARABISKA_CAR = 'RISK_ONE_ARABISKA_CAR';
    const SPANISH_RISK_ONE = 'SPANISH_RISK_ONE';
    const RISK_TWO_ARABISKA_CAR = 'RISK_TWO_ARABISKA_CAR';
    const RISK_ONE_TWO_COMBO = 'RISK_ONE_TWO_COMBO';
    const RISK_ONE_TWO_COMBO_ENGLISH = 'RISK_ONE_TWO_COMBO_ENGLISH';
    const YKB_GRUNDKURS_140_H = 'YKB_GRUNDKURS_140_H';
    const YKB_FORTUTBILDNING_35_H = 'YKB_FORTUTBILDNING_35_H';

    /**
     * MC
     */
    const DRIVING_LESSON_MC = 'DRIVING_LESSON_MC';
    const BORROW_MC_DRIVING_TEST = 'BORROW_MC_DRIVING_TEST';
    const DRIVING_TEST_WARM_UP_MC = 'DRIVING_TEST_WARM_UP_CAR_MC';
    const RISK_ONE_MC = 'RISK_ONE_MC';
    const RISK_TWO_MC = 'RISK_TWO_MC';
    const ENROLLMENT_MC = 'ENROLLMENT_MC';
    const LITERATURE_MC = 'LITERATURE_MC';
    const MANDATORY_EXPENSES_MC = 'MANDATORY_EXPENSES_MC';
    const INTRODUCTION_MC = 'INTRODUCTION_MC';

    /**
     * MOPED
     */
    const MOPED_PACKAGE = 'MOPED_PACKAGE';
    const MANDATORY_EXPENSES_MOPED = 'MANDATORY_EXPENSES_MOPED';
}
